upstream loyalty {
    {{ range getvs "/loyalty/*" }}
        server {{ . }};
    {{ end }} 
}

server {
    listen 80;
    server_name loyalty.api.tomtop.com;

    location / {
        proxy_pass http://loyalty;
    }

    access_log /data/logs/nginx/loyalty.api.tomtop.com_access.log json;
    error_log /data/logs/nginx/loyalty.api.tomtop.com_error.log;
}
