upstream member {
    {{ range getvs "/member/*" }}
        server {{ . }};
    {{ end }} 
}

server {
    listen 80;
    server_name member.api.tomtop.com;

    location / {
        proxy_pass http://member;
    }

    access_log /data/logs/nginx/member.api.tomtop.com_access.log json;
    error_log /data/logs/nginx/member.api.tomtop.com_error.log;
}
