upstream cafagom {
    {{ range getvs "/cafagom/*" }}
        server {{ . }};
    {{ end }}
}

server {
    listen 80;
    server_name mtest.cafago.com;

    access_log /data/logs/nginx/mtest.cafago.com_access.log  json;
    error_log /data/logs/nginx/mtest.cafago.com_error.log;

    if ($host = "cafago.com") {
        rewrite ^/(.*)$ http://mtest.cafago.com/$1 permanent;
    }

    location / {
        proxy_pass http://cafagom;
    }

    location /activity/ {
        proxy_pass            http://www.tomtop.com;
    }

    location /sitemap.xml {
        proxy_set_header Host s3-us-west-2.amazonaws.com;
        proxy_pass     https://s3-us-west-2.amazonaws.com/sitemap.website.com/cafago/sitemap.xml;
    }

    location ^~ /sitemap/ {
        proxy_set_header Host s3-us-west-2.amazonaws.com;
        proxy_pass     https://s3-us-west-2.amazonaws.com/sitemap.website.com/cafago/sitemap/;
    }
}



server {
    listen 443;
    server_name mtest.cafago.com;

    ssl                  on;
    ssl_certificate      server_cafago.pem;
    ssl_certificate_key  server_cafago.key;
    ssl_session_timeout  5m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers  HIGH:!RC4:!MD5:!aNULL:!eNULL:!NULL:!DH:!EDH:!EXP:+MEDIUM;
    ssl_prefer_server_ciphers   on;

     location / {
        proxy_pass http://cafagom;
     }

     access_log /data/logs/nginx/mtest.cafago.com_access.log  json;
     error_log /data/logs/nginx/mtest.cafago.com_error.log;
}
