upstream review {
    {{ range getvs "/review/*" }}
        server {{ . }};
    {{ end }} 
}

server {
    listen 80;
    server_name review.api.tomtop.com;

    location / {
        proxy_pass http://review;
    }

    access_log /data/logs/nginx/review.api.tomtop.com_access.log json;
    error_log /data/logs/nginx/review.api.tomtop.com_error.log;
}
