FROM 192.168.221.134:5000/tomtop/www:base
MAINTAINER huangjie 2853718645@qq.com

RUN useradd www  && \
    mkdir /data/logs/{php,nginx} -p && \
    mkdir /data/www

COPY php_config/php.ini /etc/php.ini
COPY php_config/php-fpm.conf /etc/php-fpm.conf
COPY php_config/redis.ini /etc/php-zts.d/redis.ini
COPY php_config/www.conf /etc/php-fpm.d/www.conf
COPY nginx_config/nginx.conf /etc/nginx/nginx.conf
COPY supervisord.conf /etc/supervisord.conf

EXPOSE 80

ENV MyPro template
COPY nginx_config/test.${MyPro}.com.conf /etc/nginx/conf.d/test.${MyPro}.com.conf
COPY src /data/www/
RUN chown -R www.www /data/www/

CMD ["supervisord", "-n"]
