upstream ipn {
    {{ range getvs "/ipn/*" }}
        server {{ . }};
    {{ end }} 
}

server {
    listen 80;
    server_name ipn.api.tomtop.com;

    location / {
        proxy_pass http://ipn;
    }

    access_log /data/logs/nginx/ipn.api.tomtop.com_access.log json;
    error_log /data/logs/nginx/ipn.api.tomtop.com_error.log;
}
