upstream report {
    {{ range getvs "/report/*" }}
        server {{ . }};
    {{ end }} 
}

server {
    listen 80;
    server_name report.api.tomtop.com;

    location / {
        proxy_pass http://report;
    }

    access_log /data/logs/nginx/report.api.tomtop.com_access.log json;
    error_log /data/logs/nginx/report.api.tomtop.com_error.log;
}
