upstream search-job {
    {{ range getvs "/search-job/*" }}
        server {{ . }};
    {{ end }} 
}

server {
    listen 80;
    server_name search-job.api.tomtop.com;

    location / {
        proxy_pass http://search-job;
    }

    access_log /data/logs/nginx/search-job.api.tomtop.com_access.log json;
    error_log /data/logs/nginx/search-job.api.tomtop.com_error.log;
}
